// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function InvokeFunction(arg1:string,arg2:string,arg3:Array<string>):Promise<main.InvokeResponse>;

export function RuntimeSnapshot():Promise<main.RuntimeSnapshot>;

export function SelectAndDeployFunction(arg1:string):Promise<main.RuntimeSnapshot>;
