// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function InvokeFunction(arg1, arg2, arg3) {
  return window['go']['main']['App']['InvokeFunction'](arg1, arg2, arg3);
}

export function RuntimeSnapshot() {
  return window['go']['main']['App']['RuntimeSnapshot']();
}

export function SelectAndDeployFunction(arg1) {
  return window['go']['main']['App']['SelectAndDeployFunction'](arg1);
}
